### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "id" is null

### ISSUE THREAD

**Issue by Protonull** [Protonull/CivVoxelMap#2]
Getting the following error, which I cannot seem to replicate on vanilla VoxelMap:
```
[02:42:13] [Voxelmap WorldMap Calculation Thread 2/ERROR]: Uncaught exception in thread "Voxelmap WorldMap Calculation Thread 2"
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "id" is null
	at com.mamiyaotaru.voxelmap.persistent.CompressibleMapData.createKeyFromCurrentBlocks(CompressibleMapData.java:409) ~[voxelmap-1.20.4-1.12.17-a5190798dd90ee9.jar:?]
	at com.mamiyaotaru.voxelmap.persistent.CompressibleMapData.getStateToInt(CompressibleMapData.java:335) ~[voxelmap-1.20.4-1.12.17-a5190798dd90ee9.jar:?]
	at com.mamiyaotaru.voxelmap.persistent.CachedRegion.doSave(CachedRegion.java:543) ~[voxelmap-1.20.4-1.12.17-a5190798dd90ee9.jar:?]
	at com.mamiyaotaru.voxelmap.persistent.CachedRegion.lambda$saveData$4(CachedRegion.java:520) ~[voxelmap-1.20.4-1.12.17-a5190798dd90ee9.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[02:42:13] [Voxelmap WorldMap Calculation Thread 4/ERROR]: Uncaught exception in thread "Voxelmap WorldMap Calculation Thread 4"
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "id" is null
	at com.mamiyaotaru.voxelmap.persistent.CompressibleMapData.createKeyFromCurrentBlocks(CompressibleMapData.java:409) ~[voxelmap-1.20.4-1.12.17-a5190798dd90ee9.jar:?]
	at com.mamiyaotaru.voxelmap.persistent.CompressibleMapData.getStateToInt(CompressibleMapData.java:335) ~[voxelmap-1.20.4-1.12.17-a5190798dd90ee9.jar:?]
	at com.mamiyaotaru.voxelmap.persistent.CachedRegion.doSave(CachedRegion.java:543) ~[voxelmap-1.20.4-1.12.17-a5190798dd90ee9.jar:?]
	at com.mamiyaotaru.voxelmap.persistent.CachedRegion.lambda$saveData$4(CachedRegion.java:520) ~[voxelmap-1.20.4-1.12.17-a5190798dd90ee9.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by Protonull** [comment]
Should be fixed by 6343774306bc5ae8077cde8de625f794714b2801
